spring:
  application:
    name: SKILLS-SERVICE

  #DATABASE PROPERTIES
  datasource:
    username: root
    password: izel2002
    url: jdbc:mysql://localhost:3306/skillapse_skills
  jpa:
    hibernate:
      ddl-auto: update

  #ADMIN-SERVER REGISTER
  boot:
    admin:
      client:
        url: 'http://localhost:1111'

management:
  endpoints:
    web:
      exposure:
        include: "*"

secret.key: lQ/septmqpU+XgqEQA8KirEJsEVJOdH65fBVCQbMY+A=

server:
  port: 8082