spring:
  application:
    name: user-service

  #Redis config
  data:
    redis:
      host: localhost
      port: 6379
      password:

  #Admin config
  boot:
    admin:
      client:
        url: 'http://localhost:1111'

  datasource:
    url: jdbc:mysql://localhost:3306/skillapse_user
    username: root
    password: izel2002
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:

    host: smtp.gmail.com
    port: 587
    username: mailtobeiskills@gmail.com
    password: xkbg wzzg eyay syxf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

    security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1076027104828-70fokbgpf0hfpgdfrg1k9fd3a73bgsqj.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
secret.key: lQ/septmqpU+XgqEQA8KirEJsEVJOdH65fBVCQbMY+A=
