spring:
  application:
    name: User-Service-Config

#Config server git configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HariPrasanth290905/ConfigServer.git
          username: HariPrasanth290905
          password: ${GIT_TOKEN}

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"